[package]
edition.workspace = true
name = "nix_rs"
version = "0.1.8"
license.workspace = true
repository.workspace = true
description = "Rust library for interacting with the Nix command"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if.workspace = true
regex = "1.9.3"
os_info = "3.7.0"
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
tokio = { version = "1.29", features = ["full"], optional = true }
tracing.workspace = true
url = { version = "2.4", features = ["serde"] }
colored = { version = "2.0", optional = true }
shell-words = { version = "1.1.0", optional = true }
is_proc_translated = { version = "0.1.1", optional = true }
sysinfo.version = "0.29.10"
bytesize.workspace = true

[features]
ssr = ["dep:tokio", "dep:colored", "dep:shell-words", "dep:is_proc_translated"]
